### ISSUE TITLE
Is it planned to mock URL.revokeObjectURL?

### ISSUE THREAD

**Issue by NandoSangenetto** [developit/jsdom-worker#16]
Is it planned to mock URL.revokeObjectURL?

Just asking if there is a reason not to include it.

**Comment by nandosangenetto** [comment]
By the way, I tried to mock `window.URL.revokeObjectURL = jest.fn();`.
The error message changes, now I'm getting:

```
TypeError: Cannot read properties of undefined (reading 'match')
    at k (/Users/fsangenetto/Sites/explorer/node_modules/jsdom-worker/src/index.js:40:21)
    at new Object.<anonymous>.i.Worker (/Users/fsangenetto/Sites/explorer/node_modules/jsdom-worker/src/index.js:124:13)
    at c (/Users/fsangenetto/Sites/explorer/node_modules/@koale/useworker/dist/index.js:1:1970)
    at /Users/fsangenetto/Sites/explorer/node_modules/@koale/useworker/dist/index.js:1:3403
    at fetchTransactions (/Users/fsangenetto/Sites/explorer/src/hooks/useRecentTransactions.ts:58:47)
    at /Users/fsangenetto/Sites/explorer/src/hooks/useRecentTransactions.ts:63:9
    at commitHookEffectListMount (/Users/fsangenetto/Sites/explorer/node_modules/react-dom/cjs/react-dom.development.js:23150:26)
    at commitPassiveMountOnFiber (/Users/fsangenetto/Sites/explorer/node_modules/react-dom/cjs/react-dom.development.js:24931:11)
    at commitPassiveMountEffects_complete (/Users/fsangenetto/Sites/explorer/node_modules/react-dom/cjs/react-dom.development.js:24891:9)
    at commitPassiveMountEffects_begin (/Users/fsangenetto/Sites/explorer/node_modules/react-dom/cjs/react-dom.development.js:24878:7)
    at commitPassiveMountEffects (/Users/fsangenetto/Sites/explorer/node_modules/react-dom/cjs/react-dom.development.js:24866:3)
    at flushPassiveEffectsImpl (/Users/fsangenetto/Sites/explorer/node_modules/react-dom/cjs/react-dom.development.js:27039:3)
    at flushPassiveEffects (/Users/fsangenetto/Sites/explorer/node_modules/react-dom/cjs/react-dom.development.js:26984:14)
    at /Users/fsangenetto/Sites/explorer/node_modules/react-dom/cjs/react-dom.development.js:26769:9
    at flushActQueue (/Users/fsangenetto/Sites/explorer/node_modules/react/cjs/react.development.js:2667:24)
    at act (/Users/fsangenetto/Sites/explorer/node_modules/react/cjs/react.development.js:2582:11)
    at /Users/fsangenetto/Sites/explorer/node_modules/@testing-library/react/dist/act-compat.js:63:25
    at WS.send (/Users/fsangenetto/Sites/explorer/node_modules/jest-websocket-mock/lib/jest-websocket-mock.cjs.js:165:5)
    at Object.<anonymous> (/Users/fsangenetto/Sites/explorer/src/hooks/useRecentTransactions.test.tsx:41:18)```

**Comment by geminiyellow** [comment]
yes, same `revokeObjectURL` error here.

**Comment by developit** [comment]
I opened PRs to fix both issues.
