### ISSUE TITLE
Cannot import jsdom-worker with --experimental-vm-modules

### ISSUE THREAD

**Issue by Amatewasu** [developit/jsdom-worker#22]
In order to be allowed to use `import.meta.url` in my jest tests, I turned on the option `--experimental-vm-modules`. But thereby I cannot import jsdom-worker anymore.

I have the following stack trace:
```
FAIL  src/anonymized-path/anonymized.test.tsx
  ● Test suite failed to run
                                                                                                                                                              
    Must use import to load ES Module: C:\anonymized-path\anonymized\node_modules\node-fetch\src\index.js

      4 | import { enableFetchMocks } from 'jest-fetch-mock';
      5 | import { readFileSync, readdirSync } from 'fs';
    > 6 | import 'jsdom-worker';
        | ^
      7 | import { getPathFromPublic } from 'utils/helpers';
      8 |
      9 | /* Wasm jest problems - the function locate file returns C:\ instead of localhost when testing with jest

      at Runtime.requireModule (node_modules/jest-runtime/build/index.js:972:21)
      at Object.<anonymous> (node_modules/jsdom-worker/dist/jsdom-worker.js:1:89)
      at Object.<anonymous> (src/setupTests.ts:6:1)
```

Would you have insight how to solve this issue?

```
$ node -v
v17.9.1
$ npm -v
8.11.0
```

**Comment by LeonardoRick** [comment]
Hey @Amatewasu did you find any solution to this problem? It's weird still having problems to use ESM modules in 2024 lol

**Comment by Amatewasu** [comment]
@LeonardoRick I do not use jest anymore but the [bun test suite](https://bun.sh/docs/cli/test) with [happy-dom](https://github.com/capricorn86/happy-dom)
