### ISSUE TITLE
ReferenceError: cov_2a33nrkdo3 is not defined

### ISSUE THREAD

**Issue by LeonardoRick** [developit/jsdom-worker#26]
```
 console.error
    ReferenceError: cov_2a33nrkdo3 is not defined
        at parseArgs (eval at <anonymous> (/Users/leonardorick/Documents/git/others/utils/javascript/node_modules/jsdom-worker/src/index.js:130:6), <anonymous>:9:3)
        at Object.eval (eval at <anonymous> (/Users/leonardorick/Documents/git/others/utils/javascript/node_modules/jsdom-worker/src/index.js:130:6), <anonymous>:6:23)
        at /Users/leonardorick/Documents/git/others/utils/javascript/node_modules/jsdom-worker/src/index.js:139:2
```

to reproduce you can go to [my repo](https://github.com/LeonardoRick/utils/blob/main/javascript/src/run-on-worker.js) and run the tests as

```
npm run test -- --coverage
```

The error only appear when I try to run the tests with coverage enabled and it looks really like an internal thing breaking that I couldn't understand the relation with the coverage flag

**Comment by cywcd** [comment]
```
console.error
    ReferenceError: cov_hu7jftp2e is not defined
        at eval (eval at <anonymous> (E:\fork-project\code\fe-ap-utils\node_modules\jsdom-worker\dist\jsdom-worker.js:1:2403), <anonymous>:6:5)
        at Object.eval (eval at <anonymous> (E:\fork-project\code\fe-ap-utils\node_modules\jsdom-worker\dist\jsdom-worker.js:1:2403), <anonymous>:64:5
```

I also encountered the same problem, there are solutions?

**Comment by marabesi** [comment]
Not sure if that will help or not, but in my project I had to unpack the jsdom-worker into my project. I had to bring all the package and its dependencies instead of using the import from npm. The project is available here: https://github.com/marabesi/json-tool.

<img width="704" alt="image" src="https://github.com/user-attachments/assets/a28ca656-54e2-4ac3-9a1f-2a4841ffe1dc">

and the dependencies:

<img width="797" alt="image" src="https://github.com/user-attachments/assets/5a9b4046-af89-4334-8c2f-7878d3a54a38">
