### ISSUE TITLE
Error when running with jest

### ISSUE THREAD

**Issue by AaronVasquez** [developit/jsdom-worker#4]
```js
console.error node_modules/jsdom-worker/dist/jsdom-inline-worker.js:1
    Error: only absolute urls are supported
        at /Users/aaronvasquez/Oyster/webnode/directories/node_modules/node-fetch/index.js:54:10
        at new Promise (<anonymous>)
        at new Fetch (/Users/aaronvasquez/Oyster/webnode/directories/node_modules/node-fetch/index.js:49:9)
        at Fetch (/Users/aaronvasquez/Oyster/webnode/directories/node_modules/node-fetch/index.js:37:10)
        at Object.<anonymous>.global.fetch (/Users/aaronvasquez/Oyster/webnode/directories/node_modules/jsdom-worker/dist/jsdom-inline-worker.js:1:876)
        at new Worker (/Users/aaronvasquez/Oyster/webnode/directories/node_modules/jsdom-worker/dist/jsdom-inline-worker.js:1:1780)
        at /Users/aaronvasquez/Oyster/webnode/directories/src/utils/bg-worker/index.js:12:29
        at new Promise (<anonymous>)
        at performTask (/Users/aaronvasquez/Oyster/webnode/directories/src/utils/bg-worker/index.js:11:5)
        at Object.<anonymous> (/Users/aaronvasquez/Oyster/webnode/directories/src/utils/bg-worker/bg-worker.test.js:9:29)
        at resolve (/Users/aaronvasquez/Oyster/webnode/directories/node_modules/jest-jasmine2/build/queueRunner.js:38:12)
        at new Promise (<anonymous>)
        at mapper (/Users/aaronvasquez/Oyster/webnode/directories/node_modules/jest-jasmine2/build/queueRunner.js:31:21)
        at Promise.resolve.then.el (/Users/aaronvasquez/Oyster/webnode/directories/node_modules/p-map/index.js:46:16)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
```

This is what I have in my test file:
```js
import "jsdom-worker";
```

**Comment by developit** [comment]
What are you passing to `new Worker()`?

**Comment by SpaceHexagon** [comment]
I ran into the same issue. 
Looking here, https://github.com/bitinn/node-fetch/blob/1d4ab5a0de0df991f92f1f30efd5f4815bbcdb71/src/request.js#L161 I see it needs to have a protocol specified. The problem is that `file://` isn't supported 
```
Error: only http(s) protocols are supported
          at ...node_modules\jsdom-worker\node_modules\node-fetch\index.js:58:10
```

**Comment by developit** [comment]
Ah - we'll need to have self.fetch in the worker context patch URLs it receives to rebase them.

**Comment by neptunian** [comment]
is there a workaround or this possible to fix?

**Comment by astagi** [comment]
This is an old issue, but I have the same problem in my code (I opened a similar issue #14 ). In my tests tried to load a module where my Worker code lives but Node fetch seems to work only with absolute urls. I mocked `fetch` to load my module source and then I compiled it using babel/core. I also had to modify jsdom-worker source code to make it work. That wasn't a clean solution :( Since I started my project using Webpack worker-loader (https://webpack.js.org/loaders/worker-loader/) and using Jest as test framework, I created a little transformer to test workers inspired by jsdom-worker (https://github.com/astagi/workerloader-jest-transformer). I hope this may help someone! (note that `workerloader-jest-transformer` is highly experimental, any contribution and advice would be greatly appreciated)

**Comment by markhalliwell** [comment]
I was able to silence these console errors when running tests by adding [@whatwg-node/node-fetch](https://www.npmjs.com/package/@whatwg-node/fetch) and polyfilling it in a jest setup file.

```bash
npm i -D @whatwg-node/fetch
```

```js
// jest.config.js
module.exports = {
  // ...otherConfig,
  setupFilesAfterEnv: [
    'jsdom-worker',
    '<rootDir>/jest.setup.js',
  ],
};
```

```js
// jest.setup.js
import { fetch } from '@whatwg-node/node-fetch';

// Polyfill fetch.
if (!window.fetch) {
  window.fetch = fetch;
}

```

This is possible because `jsdom-worker` defaults to using an existing global fetch implementation or `node-fetch` as its backup (where these console errors come from) https://github.com/developit/jsdom-worker/blob/aaf2874b87b4ab6d6d3113cd816e510d447331d3/src/index.js#L37

As long as the global `fetch` is polyfilled with whatever you need/want prior to a Worker being created using `jsdom-worker`, you shouldn't get this error message anymore.
